name: Deploy (beta.destinyitemmanager.com)
on:
  push:
    branches:
      - master

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup and Install
        uses: ./.github/workflows/setup-and-install.yml

      - name: Versioning
        uses: ./.github/workflows/versioning.yml
        with:
          flavor: beta
          patch: false

      - name: Build and Deploy
        uses: ./.github/workflows/build-and-deploy.yml
        with:
          APP_DOMAIN: beta.destinyitemmanager.com
          flavor: beta
