name: Deploy (app.destinyitemmanager.com)

on:
  schedule:
    # Deploy at 5pm Sunday PST, which is 1am Monday UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * 1'
  workflow_dispatch:
    inputs:
      patch:
        description: 'Should this be a patch release?'
        type: boolean
        required: true
        default: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup and Install
        uses: DestinyItemManager/DIM/.github/workflows/setup-and-install.yml
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

      - name: Versioning
        uses: DestinyItemManager/DIM/.github/workflows/versioning.yml
        with:
          flavor: release
          patch: ${{ inputs.patch }}

      - name: Generate Release Notes
        uses: DestinyItemManager/DIM/.github/workflows/generate-release-notes.yml

      - name: Build and Deploy
        uses: DestinyItemManager/DIM/.github/workflows/build-and-deploy.yml
        with:
          APP_DOMAIN: app.destinyitemmanager.com
          flavor: release
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_OAUTH_CLIENT_ID: ${{ secrets.WEB_OAUTH_CLIENT_ID }}
          WEB_OAUTH_CLIENT_SECRET: ${{ secrets.WEB_OAUTH_CLIENT_SECRET }}
          DIM_API_KEY: ${{ secrets.DIM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
