name: Deploy Beta

on:
  push:
    branches:
      - master

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-beta:
    uses: ./.github/workflows/deploy.yml
    with:
      flavor: beta
      patch: false
      APP_DOMAIN: beta.destinyitemmanager.com
