name: Deploy Prod

on:
  workflow_dispatch:
    inputs:
      patch:
        description: 'Should this be a patch release?'
        required: true
        default: 'true'
  schedule:
    # Deploy at 5pm Sunday PST, which is 1am Monday UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * 1'

jobs:
  deploy-beta:
    uses: ./.github/workflows/deploy.yml
    with:
      flavor: release
      APP_DOMAIN: app.destinyitemmanager.com
      patch: ${{ inputs.patch }}
