name: Deploy (app.destinyitemmanager.com)

on:
  schedule:
    # Deploy at 5pm Sunday PST, which is 1am Monday UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * 1'
  workflow_dispatch:
    inputs:
      patch:
        description: 'Should this be a patch release?'
        type: boolean
        required: true
        default: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Install
        uses: ./.github/workflows/setup-and-install.yml

      - name: Versioning
        uses: ./.github/workflows/versioning.yml
        with:
          flavor: release
          patch: inputs.patch

      - name: Generate Release Notes
        uses: ./.github/workflows/generate-release-notes.yml

      - name: Build and Deploy
        uses: ./.github/workflows/build-and-deploy.yml
        with:
          APP_DOMAIN: app.destinyitemmanager.com
          flavor: release
