name: Deploy (beta.destinyitemmanager.com)
on:
  push:
    branches:
      - master

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup and Install
        uses: DestinyItemManager/DIM/.github/workflows/setup-and-install.yml
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

      - name: Versioning
        uses: DestinyItemManager/DIM/.github/workflows/versioning.yml
        with:
          flavor: beta
          patch: false

      - name: Build and Deploy
        uses: DestinyItemManager/DIM/.github/workflows/build-and-deploy.yml
        with:
          APP_DOMAIN: beta.destinyitemmanager.com
          flavor: beta
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_OAUTH_CLIENT_ID: ${{ secrets.WEB_OAUTH_CLIENT_ID }}
          WEB_OAUTH_CLIENT_SECRET: ${{ secrets.WEB_OAUTH_CLIENT_SECRET }}
          DIM_API_KEY: ${{ secrets.DIM_API_KEY }}
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
