name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Install
        uses: ./.github/workflows/setup-and-install.yml

      - name: Versioning
        uses: ./.github/workflows/versioning.yml
        with:
          flavor: beta
          patch: false

      - name: Build beta
        run: yarn build:beta
        env:
          PR_BUILD: true

      - name: Upload webpack stats artifact
        uses: relative-ci/agent-upload-artifact-action@v1
        with:
          webpackStatsFile: ./webpack-stats.json

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Install
        uses: ./.github/workflows/setup-and-install.yml

      - name: Jest Annotations & Coverage
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          coverage-comment: false

      - name: Jest Test
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Install
        uses: ./.github/workflows/setup-and-install.yml

      - name: Save ESLint Report JSON
        run: yarn lint-report:cached
        continue-on-error: true

      - name: Annotate ESLint Results
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
          fail-on-warning: true

      - name: ESLint
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: yarn lintcached
