name: RelativeCI

on:
  workflow_run:
    workflows: ["PR Build"]
    types:
      - completed

jobs:
  haslabel:
    runs-on: ubuntu-latest
    outputs:
      relative-ci: ${{ steps.haslabel.outputs.labeled-relative-ci }}
    steps:
      - name: Labeled to relative-ci
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'relative-ci'

  relative-ci:
    runs-on: ubuntu-latest
    needs: haslabel
    if: needs.haslabel.outputs.relative-ci
    steps:
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
